### ISSUE TITLE
Self-hosted installation

### ISSUE THREAD

**Issue by itamarst** [jameslittle230/stork#101]
Hi,

I'd rather host the JavaScript for Stork on my domain; given I'm already on Netlify with its own CDN, opening more HTTP connections seems unnecessary. In addition, having a specific version means I can upgrade on my own schedule (versioned CDN URLs would help with the latter, but I'd still prefer self-hosted).

It sounds from the docs like this is not possible now, but it would be cool if it was.

Thanks!

**Comment by fauno** [comment]
Also browsers are in the process of partitioning caches, so the gains from hosting the js+wasm files on a single server are going to disappear.

Reference: https://developers.google.com/web/updates/2020/10/http-cache-partitioning

**Comment by jameslittle230** [comment]
Self-hosted Stork is definitely something I want to build! I've been focusing on a more low-code experience for the 1.0.0, but I completely recognize the value of self-hosting code.

For now (and I haven't tried this for self-hosting, so use at your own risk) -- the whole project (including the final JS file and the WASM blob) can be built from source. Tweaking the build a little bit would probably get you most of the way there, and hosting it that way is fine by me (although I won't be able to help you out if you run into issues).

The biggest concern would be if you update your index without updating the WASM blob loaded on your site. If you did that, Stork might fail in unexpected ways.

**Comment by jameslittle230** [comment]
There are a few bits of friction that I'd like to solve before advertising self-hosted Stork as a supportable integration:
- Documentation that describes how to serve WASM files correctly. All modern browsers require that WASM files must be served with a `Content-Type: application/wasm` header. For Netlify, this isn't [too complicated to specify](https://docs.netlify.com/routing/headers/), but I don't think Github Pages supports custom headers, for example, so they wouldn't be able to do this. I'm not sure about Vercel, Fastly, or other CDNs, either.
    - If self-hosted Stork required that you host both the WASM and the JS, Stork would need a way to configure where the WASM file could be found; right now, it's hardcoded into the JS. (This wouldn't be too complex, but it's still a blocker.)

- In lieu of serving both a JS and a WASM file, Stork could bake the WASM blob into the JS as an `ArrayBuffer`. Right now, the WASM blob is far too large for this: in development mode, Webpack outputs a 50 MB JS file, and in production mode, Webpack throws an out-of-memory error trying to build the JS file.

**Comment by styfle** [comment]
I think self hosting is a great idea!

> must be served with a Content-Type: application/wasm header....I'm not sure about Vercel

Vercel already supports the [correct content type](https://user-images.githubusercontent.com/229881/104775684-c20ea900-5746-11eb-90a6-500a5e8bb4d9.png) automatically.

> Stork could bake the WASM blob into the JS

This is not desirable because JS takes longer to parse than WASM.

I would prefer no JS and instead explain how invoke the wasm functions from JS.

**Comment by Jieiku** [comment]
Just wanted to add that you can self host stork easily by adding this to the bottom of your stork.js file:

```js
const baseUrl = document.location.origin;
stork
.initialize(baseUrl + "/stork.wasm")
.then(() => {
    console.log("Finished downloading WASM");
})
.catch(e => {
    console.error(e);
}); // download WASM
stork.register("stork",baseUrl + "/stork.st");
```
