### ISSUE TITLE
Fatal error when parsing curly quotes in config.toml

### ISSUE THREAD

**Issue by chmaynard** [jameslittle230/stork#104]
U+201C and U+201D are left and right double quotation marks. Stork 1.0.0 doesn't seem to like them in the config.toml file.

```Could not generate index: unexpected character found: `\u{201c}` at line 4 column 17```

**Comment by reese** [comment]
Do you have an example TOML to reproduce this? I would imagine this is an error coming from the `toml` crate, but that crate is pretty heavily used so having a minimum test case here would be helpful.

**Comment by chmaynard** [comment]
If the TOML specification states that string values must use ASCII quotes, then I think we can simply close this issue as not to be fixed.

**Comment by reese** [comment]
Based on [the spec](https://toml.io/en/v1.0.0-rc.3#string), it does look like Unicode quotes can only be _inside_ the string and that yes, the surrounding quotes have to be ASCII quotes, so I agree that this should be good to close.

**Comment by jameslittle230** [comment]
Thanks for the investigation & clarification - I was interpreting the question as asking about curly quotes _within_ a quoted TOML string, which _should_ be valid. But curly quotes to delimit a string value in TOML itself is not.
