### ISSUE TITLE
"HTML selector is not present in the document"

### ISSUE THREAD

**Issue by fauno** [jameslittle230/stork#105]
While writing jekyll-stork #96 I found out that indexing HTML requires the `<main>` tag to be present, but it seems that if a single page doesn't have it the whole indexing fails.  The error is not very helpful, I had to read the code to find out about the `<main>` tag.

The issue is that it doesn't tell me which page is missing it. Could it tell the path and maybe even skip the page?

I'm wondering if it would be better to index the source files... from the documentation I understand that Stork can index the frontmatter, but at least on my sites there's metadata there that sometimes doesn't end up on the public site so I prefer to index the generated pages (mimicking what a web crawler would do).

**Comment by chmaynard** [comment]
Private communication with the author confirms this:

An HTML selector is a way of identifying a specific HTML tag (or a group of tags), much the way you might do in CSS: you write `.myClass` to identify all the elements with the class of `myClass` or `div#thisId` to get the <div> element with the ID of `thisID`, etc. For more information, see this link[0]

When indexing HTML files, Stork will parse all text within a certain selector to avoid indexing all the content on the page (you can imagine you might not want to index your navigation bar, for example). Stork defaults to parsing all content within the <main> tag. If Stork can’t find a <main> tag, you’ll see the error you’ve run into. (And yes, as Stork is parsing an HTML file, it will filter out markup and style info along the way)

**Comment by fauno** [comment]
Thanks! I understand why it's done like this, the issue is that Stork doesn't tell you which file is missing the tag and it cancels the whole indexing altogether.

**Comment by jameslittle230** [comment]
Thanks for reporting, @fauno,  and thanks for clarifying what's going on @chmaynard! I have some docs work to do to describe Stork's HTML document handling (and the corresponding `html_selector` configuration option), but this is also a bug that I'll try to get out in 1.0.2 today.

Best,
James

**Comment by chmaynard** [comment]
To fix this problem in my Jekyll project, I added `<main>` to the `default.html` layout as follows:
```
<main>
<div class="content">
{{ content }}
</div>
</main>
```
