### ISSUE TITLE
Index web content given a list of urls

### ISSUE THREAD

**Issue by jameslittle230** [jameslittle230/stork#11]

**Comment by ggoodman** [comment]
This library looks amazing. Do you envision supporting a use-case where the index can be built programmatically? An example might be content that is dynamically generated and is never serialized to disk?

**Comment by jameslittle230** [comment]
@ggoodman - I don't think that's in scope for Stork, but I'm also not quite sure I understand what you mean.

If you wouldn't mind, could you open a new [Discussion](https://github.com/jameslittle230/stork/discussions) describing what you're envisioning? I'd love to help clarify the scope of Stork. (I don't think this issue is quite the right place for this, which is why I'm suggesting moving to Discussions.)

Thanks very much!
James
