### ISSUE TITLE
Helpfully handle hyphens

### ISSUE THREAD

**Issue by karlwilcox** [jameslittle230/stork#110]
James, excellent piece of work, thank you. I have incorporated into the search function for a gallery of user-submitted coats of arms (https://drawshield.net/gallery/)

My suggestion might be covered by your goal of "fuzzy" search, but a simple "quick hit" might be to treat hyphenated words as separate tokens (unless the hyphen is at the end of a line, perhaps). At the moment a search for "Hull" does NOT find "Kingston-upon-Hull" which I think it should...?

I am fortunate that I can "condition" my input as I programmatically create the .toml file, which includes the content and can just do a search and replace before running stork, but I wouldn't have this ability with file based input.

Hope this is useful,

Kind regards,

Karl

**Comment by jameslittle230** [comment]
@karlwilcox - I like this idea! In prose, hyphens and spaces often serve similar purposes (at least in the context of splitting up words to search for). I might want to poke a bit to make sure there aren't any weird edge cases, but I think this would go a long way to improving search behavior

Also - your site looks really cool -- exactly what the internet should be used for :)

**Comment by jameslittle230** [comment]
This will be released in version 1.0.3!
