### ISSUE TITLE
Config should acept folder path and index all files pr by extension inside the folder 

### ISSUE THREAD

**Issue by vprdnew** [jameslittle230/stork#117]
The config can have the feature to pick the files inside the folder mentioned which will reduce the process of integration. We found it difficult while working with MD files indexing of more than 2k numbers. 

Thanks!

**Comment by jameslittle230** [comment]
Hi @vprdnew! I'm going to close this as a duplicate -- I think this is the same feature request as #9!

The "filter by file extension" thing is a good addition, though, and I'll add a note to the other issue so they can be tracked together.

Thanks for writing in!
James
