### ISSUE TITLE
Cut down on WASM file size by removing Debug implementations.

### ISSUE THREAD

**Issue by reese** [jameslittle230/stork#124]
I used [`twiggy`](https://github.com/rustwasm/twiggy) to take a look at the WASM file size for Stork, and it looks like a pretty big chunk of the file size is from `Debug` implementations.

```shell
stork % twiggy top target/wasm32-unknown-unknown/release/stork_search.wasm -n 10
 Shallow Bytes │ Shallow % │ Item
───────────────┼───────────┼────────────────────────────────────────────────────────────────
        539131 ┊    23.94% ┊ custom section '.debug_str'
        398637 ┊    17.70% ┊ custom section '.debug_info'
        300580 ┊    13.35% ┊ custom section '.debug_line'
        183576 ┊     8.15% ┊ custom section '.debug_ranges'
        147033 ┊     6.53% ┊ custom section '.debug_pubnames'
         55564 ┊     2.47% ┊ "function names" subsection
         51906 ┊     2.31% ┊ data[0]
         23344 ┊     1.04% ┊ custom section '.debug_aranges'
         13290 ┊     0.59% ┊ rmp_serde::decode::Deserializer<R>::read_map::hb0358e684d16b82f
         13282 ┊     0.59% ┊ rmp_serde::decode::Deserializer<R>::read_map::h7780ae98a8fdbf18
        525461 ┊    23.34% ┊ ... and 707 more.
       2251804 ┊   100.00% ┊ Σ [717 Total Rows]
```

More importantly though, the Debug implementations are almost entirely unused in the WASM binary:

```shell
stork % twiggy garbage target/wasm32-unknown-unknown/release/stork_search.wasm  
 Bytes   │ Size % │ Garbage Item
─────────┼────────┼─────────────────────────────────────────
  539131 ┊ 23.94% ┊ custom section '.debug_str'
  398637 ┊ 17.70% ┊ custom section '.debug_info'
  300580 ┊ 13.35% ┊ custom section '.debug_line'
  183576 ┊  8.15% ┊ custom section '.debug_ranges'
  147033 ┊  6.53% ┊ custom section '.debug_pubnames'
   23344 ┊  1.04% ┊ custom section '.debug_aranges'
    4883 ┊  0.22% ┊ custom section '.debug_abbrev'
     723 ┊  0.03% ┊ custom section '__wasm_bindgen_unstable'
     450 ┊  0.02% ┊ custom section '.debug_pubtypes'
      75 ┊  0.00% ┊ custom section 'producers'
 1598432 ┊ 70.98% ┊ Σ [10 Total Rows]
   51906 ┊  2.31% ┊ 1 potential false-positive data segments
```

For the most part, I think implementing `Display` on the types needed for printing error messages would be a better alternative than deriving `Debug`, since `Debug` is meant for, well, debugging, so they shouldn't be left around in the release binary.

I'd be happy to dig into this a bit more when I get the time, this is just what came up after a quick look at it.

**Comment by reese** [comment]
_Actually_ I think I'm wrong on this, I ran this on the wasm compiled in `target/`, but the files in `dist/` are _really_ what matters and they don't seem to have this issue. I believe `wasm-pack` strips debug information by default, which would explain that discrepancy. Going to close this out, apologies for the noise 🙇

**Comment by jameslittle230** [comment]
@reese - I saw this issue come in this morning and got very excited! Sorry that it didn't end up working out. 

I used twiggy a few months ago, but this is a good reminder that I should go over it again and do an audit -- there are definitely parts of the main Stork repo that shouldn't get included in the WASM build.

Thanks for writing in! :)

**Comment by reese** [comment]
Yeah for sure, I was messing around with twiggy and thought this would be a good test option, but once I spent a little bit trying to build a few different options, it unfortunately wasn't as easy of a win as I thought at first. I might poke around with it some more since it _does_ mark about 50kb of `potential false-positive data segments`, but the current file is pretty manageable as is anyways! 👍
