### ISSUE TITLE
Is there a querry limit?

### ISSUE THREAD

**Issue by geekjr** [jameslittle230/stork#132]
When i run `stork --search` with a query that is above 7 characters, I get `thread 'main' panicked at 'index 8 out of range for slice of length 7'`. Is there a query limit of 7? If so, is the query limit removable?

**Comment by jameslittle230** [comment]
Hey @geekjr! Sorry you've been hitting this -- this is definitely a bug, there's no query length limit. 

I'll look into this and try to fix it as soon as I can. If you could send your search index and your search query to me, that'd help me find & fix the bug faster -- you can attach it to this github issue or you can email it to me.

Thanks for reporting!
James

**Comment by geekjr** [comment]
Hi,
Because the index is of internal data, I can't chare it. Sorry.

**Comment by jameslittle230** [comment]
@geekjr - that's reasonable.

If possible, could you run the following command in your terminal and try the failing search again?

```bash
export RUST_BACKTRACE=1
```

I think you'll be able to see a stack trace of the crash if you set that environment variable. If you could copy & paste that stack trace here, that would also help me find the bug!

(Feel free to redact any confidential information from the stack trace if you see it.)

Thanks very much!
James

**Comment by geekjr** [comment]
Hello. It just started working.
