### ISSUE TITLE
Add a prettierignore file

### ISSUE THREAD

**Issue by jameslittle230** [jameslittle230/stork#136]
From the [Prettier docs](https://prettier.io/docs/en/cli.html):

> It’s recommended to always make sure that `prettier --write .` only formats what you want in your project. Use a .prettierignore file to ignore things that should not be formatted.

`prettier --write .` does _not_ do the right thing currently. There should be a prettierignore file so that Prettier only operates on the `/js` directory.

**Comment by jameslittle230** [comment]
cc @healeycodes

**Comment by healeycodes** [comment]
I'll take a look 😄
