### ISSUE TITLE
Intermittent CORS errors

### ISSUE THREAD

**Issue by jameslittle230** [jameslittle230/stork#143]
Opening this issue to track a few reports of intermittent CORS issues. I haven't been able to reproduce them, but I suspect that the CORS headers are being sent correctly when fetching files from Cloudfront, but not when fetching from S3 directly.

**Comment by mrmartineau** [comment]
@jameslittle230 when viewing the demo, I experienced the CORS issue. Is there anything you'd like to know in order to help debug this?

**Comment by jameslittle230** [comment]
If you have a full [HTTP archive](https://en.wikipedia.org/wiki/HAR_(file_format)) (`Export as HAR` in the web inspector) for a failing request, that might help me debug?

**Comment by mrmartineau** [comment]
Here you go: [stork-search.net.har.zip](https://github.com/jameslittle230/stork/files/6116104/stork-search.net.har.zip)

**Comment by jameslittle230** [comment]
Wow - thank you, @mrmartineau! I'll look into this.

**Comment by jameslittle230** [comment]
Closing this - I was never able to reproduce it, and nobody has reported seeing it for a while. Please open a new issue if you see this again!
