### ISSUE TITLE
Documentation: Index Format + Theory missing

### ISSUE THREAD

**Issue by cloudspeech** [jameslittle230/stork#16]
I would like to study the in-memory index format without reading through the Rust source first.

I also would like to get a basic grasp as to what theoretical approach to index-based search has been chosen (inverted index? what variant? which optimizations? etc.).

Please document these things if possible - that would be great!

**Comment by jameslittle230** [comment]
Definitely! The index format isn't currently all that complex, but as I optimize it I'll definitely put some documentation out there, likely as part of a contribution guide.

**Comment by jameslittle230** [comment]
Closing this issue for now -- I'll put something like this out there once Stork is out of beta.

**Comment by aleclarson** [comment]
👀
