### ISSUE TITLE
Stork v1.2.0 failing on Netlify

### ISSUE THREAD

**Issue by jdambron** [jameslittle230/stork#168]
Hi.

v1.2.0 is failing on Netlify following the documentation.

I get the following error:

`/stork-ubuntu-latest: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./stork-ubuntu-latest)`

I am using _Ubuntu Xenial 16.04 (default)_ to deploy my website.

Downgrading to v1.1.0 works.

**Comment by jameslittle230** [comment]
Oh no! Thanks for reporting. I think Github recently upgraded my GitHub Actions runner to Ubuntu 20.04, but Netlify is still using 16.04 for its build systems. I'll build a binary using 16.04 and replace the one on the CDN -- I'll let you know when that's finished.

Thanks again!
James

**Comment by jameslittle230** [comment]
@jdambron - I've updated the binary on the CDN and invalidated the cache. If you `wget https://files.stork-search.net/releases/v1.2.0/stork-ubuntu-latest`, it should return a binary that properly works on Netlify's build runners. Please reopen this issue and let me know if you're still having trouble.

<details>
<summary>More Details</summary>

  

I created a new binary named `stork-ubuntu-16-04` and uploaded it to the CDN, and rebuilt my Netlify site referencing that binary and watched the build succeed. I then removed the `stork-ubuntu-latest` binary (from both /releases/v1.2.0 and /releases/latest) and copied the 16-04 binary to use that same name. Finally, I created a Cloudfront cache invalidation. I verified that the two URLs were returning the same binary using the commands below:

```sh
$ curl -s https://files.stork-search.net/releases/v1.2.0/stork-ubuntu-16-04 | md5
efd99d37a25f2e71c8a8142658f13b71

$ curl -s https://files.stork-search.net/releases/v1.2.0/stork-ubuntu-latest | md5
efd99d37a25f2e71c8a8142658f13b71
```

</details>
