### ISSUE TITLE
Latest on ubuntu broken (github action runner)? v1.2.1

### ISSUE THREAD

**Issue by fliiiix** [jameslittle230/stork#178]
It seems like the latest version (1.2.1) is broken on the github action ubuntu runner. (`Current runner version: '2.278.0'`)

Downloaded from here 
```
Run wget https://files.stork-search.net/releases/latest/stork-ubuntu-latest
--2021-05-14 18:15:31--  https://files.stork-search.net/releases/latest/stork-ubuntu-latest
```

fails with:
```
Run ./stork-ubuntu-latest --build stork.toml
./stork-ubuntu-latest: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Error: Process completed with exit code 127.
``` 

I just take 1.2.0 for the moment which still works so I guess it is a regression in the latest release.

Full run:
https://github.com/Binaergewitter/serious-bg/runs/2586240245?check_suite_focus=true

**Comment by jameslittle230** [comment]
Hm - thanks for writing in, sorry you're hitting this.

I had to switch the `releases/latest/stork-ubuntu-latest` binary back to an Ubuntu 16.04 binary to support the folks using Netlify's runners: Netlify uses Ubuntu 16.04 and when Github upgraded to Ubuntu 20.04, the binary stopped working for them. (#168) The naming doesn't make sense now, and I'm not happy with it.

To reduce confusion, I've announced that I'm deprecating the `stork-ubuntu-latest` URLs in #180. To ensure you're referencing the correct Ubuntu version, please use one of the following URLs in your build system:

```
https://files.stork-search.net/releases/v1.2.1/stork-ubuntu-20-04
https://files.stork-search.net/releases/latest/stork-ubuntu-20-04
```

The former will always point to v1.2.1, and the latter will always point to the latest version of Stork, both built on Ubuntu 20.04 (and compatible with Github's runners).

Again, sorry about the sudden failures. Please let me know if the framework outlined in the discussion linked above will work for you.

**Comment by fliiiix** [comment]
Seems perfectly fine for me. I switched to the new urls and everything seems fine.

Thanks for building and maintaining stork :tada:

**Comment by shedali** [comment]
can't get this to work on github-actions with ubuntu 20.04, 18.04
`error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory` 
have tried urls mentioned

**Comment by fliiiix** [comment]
Idk but you can checkout our working example here: https://github.com/Binaergewitter/serious-bg/blob/master/.github/workflows/main.yml#L15

**Comment by shedali** [comment]
thanks mate, the reference helped and it works fine for me. (fails in nektos/act locally but can raise different issue with that repo)

**Comment by jameslittle230** [comment]
Thanks for helping, @fliiiix!

**Comment by lorenzoh** [comment]
I have run into this issue again, but it seems to be a packaging-related issue with Ubuntu 20.04. The following worked for me, so I figured I'd post in case someone else has this issue again:

```sh
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
```


As discussed in this [StackOverflow thread](https://stackoverflow.com/questions/72133316/ubuntu-22-04-libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-di)
