### ISSUE TITLE
Not enough protections to prevent users from downloading WASM twice

### ISSUE THREAD

**Issue by jameslittle230** [jameslittle230/stork#200]
Hey James! I've done some more testing with Stork 1.2.1, and I've noticed a problem that I feel I can reliably reproduce.

If you download & expand the attached [`testsite.zip`](https://github.com/jameslittle230/stork/files/7294646/testsite.zip) file and follow the steps below, I'm hoping you will be able to reproduce it as well:

```shell
cd testsite
cp theme/js/stork-1.2.1.js theme/js/stork.js
cp theme/js/stork-1.2.1.wasm theme/js/stork.wasm
python3 -m http.server
# Navigate to http://localhost:8000, open a JS console, search for "markdown", and observe that it fails.
^C
cp theme/js/stork-1.1.wasm theme/js/stork.wasm
python3 -m http.server
# Navigate to http://localhost:8000, open a JS console, search for "markdown", and observe that it succeeds.
```

The following is representative of the errors I've seen when experimenting with v1.2.x of `stork.wasm`:

```
StorkError: Could not perform search: the WASM binary failed to return search results.
    You might not be serving your search index properly.
    If you think this is an error, please file a bug: https://jil.im/storkbug
    
    The WASM binary came back with:
    Index not found. You must parse an index before performing searches with it.
```
```js
t — storkError.ts:3
(anonymous function) — searchData.ts:59
(anonymous function) — entity.ts:167
(anonymous function) — entityDom.ts:362
inputInputEvent — entityDom.ts:110
(anonymous function) — entity.ts:176
(anonymous function) — entityDom.ts:362
inputInputEvent — entityDom.ts:110
entity.ts:176
```

Do you have any idea what might be done to resolve this problem?

_Originally posted by @justinmayer in https://github.com/jameslittle230/stork/discussions/166#discussioncomment-1436770_

**Comment by justinmayer** [comment]
Many thanks for the quick response, @jameslittle230!

> This is both an integration bug and a Stork bug

I think it may also be a documentation issue. (See below.)

> In your test site, at the bottom of `index.html`, you have:
> 
> ```
>     <script>
>         stork.initialize("/theme/js/stork.wasm")
>         stork.register("sitesearch", "/search-index.st")
>     </script>
> ```

If you look at the bottom of the [Self-hosting Stork](https://stork-search.net/docs/self-hosting) documentation, you'll see that the lines above were derived from that documentation. I'm not sure where the documentation source is located, but perhaps it should be updated to reflect the appropriate steps for Stork v1.2.x?

> You should change this to:
> 
> ```
>     <script>
>         stork.initialize("/theme/js/stork.wasm")
>         stork.downloadIndex("sitesearch", "/search-index.st")
>         stork.attach("sitesearch")
>     </script>
> ```

Changing those lines appropriately does indeed resolve the problem! 🎉 
  
> One caution with hosting the WASM yourself: browsers only load WASM if the server serves them with a MIME type of `application/wasm`, which several servers won't do automatically. Python's `http.server` module [only started doing that in Python 3.8](https://bugs.python.org/issue34758), for example.

Indeed, and thank you for pointing that out. I am using Python 3.10, so that's not a problem. 🕺

**Comment by jameslittle230** [comment]
Thank you for pointing out the docs error! I'll get that fixed later today. Glad it started working well for you afterwards!:)
