### ISSUE TITLE
Stork command-line tool hangs waiting for input in some environments

### ISSUE THREAD

**Issue by Aethon** [jameslittle230/stork#207]
* On MacOS (not verified in other environments, but it seems to not have an issue on Alpine Linux)
* Calling stork from `Process.Start` in a dotnet command line project.
* Running that command line project via an MSBuild `Exec` task using `dotnet run` 

Generally, I can run the project and it all works just right, including the call to `stork`. It only hangs when executed via the path above. Sampling the hung app revealed:

```
Call graph:
    2927 Thread_2697220   DispatchQueue_1: com.apple.main-thread  (serial)
      2927 start  (in libdyld.dylib) + 1  [0x7fff712cecc9]
        2927 main  (in stork) + 630  [0x105ce27a6]
          2927 std::sys_common::backtrace::__rust_begin_short_backtrace::h129e0c80e53926b0  (in stork) + 10  [0x105cae6fa]
            2927 stork::main::hb19c90054a24d0f0  (in stork) + 2020  [0x105ce3174]
              2927 stork::build_handler::hb41e61d867ce3a82  (in stork) + 155  [0x105ce468b]
                2927 stork::build_index::hccec9371e324412d  (in stork) + 42  [0x105cec22a]
                  2927 stork::read_stdin_bytes::hd73cb3b207f849be  (in stork) + 376  [0x105cedb78]
                    2927 read  (in libsystem_kernel.dylib) + 10  [0x7fff7141081e]
```

The issue is here, I think:
https://github.com/jameslittle230/stork/blob/v1.2.1/src/bin/stork/main.rs#L130
```rust
    match (path, read_stdin()) {
        ("-", Some(stdin)) => Ok(stdin),
        ("-", None) => Err(StorkCommandLineError::InteractiveStdinNotAllowed),
        // handle ("", Some) or ("", None), perhaps
        _ => {
            let pathbuf = std::path::PathBuf::from(path);
            std::fs::read_to_string(&pathbuf)
                .map_err(|e| StorkCommandLineError::FileReadError(path.to_string(), e))
        }
```

I believe that the tuple `(path, read_stdin())` is completely resolved _before_ checking the patterns => even if the `--input` parameters is not `-`, the program will insist on the call to `read_stdin()` completing before continuing on. Perhaps `path` could be tested first and `stdin` engaged only if truly requested?

**Comment by Aethon** [comment]
# Workaround

Looking at the code, it seemed harmless to provide some bogus standard input, since the program would only use it if `--input -` was specified. I had my code just write `"no input"` to stdin after the process started and everything worked as expected. C# code example:

```cs
var storkProcess = Process.Start(
    new ProcessStartInfo("stork")
    {
        ArgumentList =
        {
            "--timing",
            "build",
            "--input", tomlFileName,
            "--output", indexFileName
        },
        RedirectStandardInput = true
    }
);

if (storkProcess == null)
    throw new Exception("Stork process could not be started");

await storkProcess.StandardInput.WriteAsync("no input");

await storkProcess.WaitForExitAsync();
```

**Comment by jameslittle230** [comment]
Hm - thanks for writing and for digging so deep on the issue! I'm planning a release this week and will try to get a fix for this in. Thanks so much!

James

**Comment by Aethon** [comment]
Thank you. And THANK YOU for this gem of a tool.

**Comment by jameslittle230** [comment]
Please let me know if you have any feedback, feature suggestions, or any other thoughts as you're using it! :)

**Comment by Aethon** [comment]
Wow! I can't believe that two years have gone by since this issue. I just was back in this code and upgraded `stork` and all is good without the workaround. Thanks again for all of your effort!
