### ISSUE TITLE
Add stork.js.map to S3 files, or remove sourcemap from JS artifact

### ISSUE THREAD

**Issue by healeycodes** [jameslittle230/stork#216]
Hi!

I'm getting this on my personal site but it looks like this is reproducible on https://stork-search.net/

1. Visit https://stork-search.net/
2. Check developer console

```text
DevTools failed to load source map: Could not load content for https://files.stork-search.net/stork.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by jameslittle230** [comment]
Yup - this is a good callout. I'll upload the sourcemap to the CDN but will poke at Webpack a bit  more to figure out how to not fetch the sourcemap in the first place.

**Comment by jameslittle230** [comment]
It looks like [I don't have to worry about](https://github.com/facebook/create-react-app/issues/2005#issuecomment-296390495) an extra sourcemap fetch taking place, which means the only remediation here is to automatically upload the sourcemap to the CDN when publishing a new version. I've added the sourcemap listing to the upload script [here](https://github.com/jameslittle230/stork/pull/239/files#diff-3a7626b045b90da99de2abef2235d0d757cd9a264db45c3c34c75adeb9649f9fR66), so I believe this issue can be closed!

Thanks for reporting, Andy ❤️
