### ISSUE TITLE
Regression: stdin no longer read

### ISSUE THREAD

**Issue by ArsenArsen** [jameslittle230/stork#251]
https://github.com/jameslittle230/stork/blob/b83157ff56dc5856703697674e9d59ad44cdcf67/stork-cli/src/io.rs#L16

See also: https://github.com/jameslittle230/stork/commit/9b629994307fb885474c757aecc98a92f7521153

**Comment by jameslittle230** [comment]
Thanks for the report - I can reproduce and will have a fix up as soon as I can.

**Comment by ArsenArsen** [comment]
thanks! <3
