### ISSUE TITLE
Usage in Rustdoc

### ISSUE THREAD

**Issue by davidhewitt** [jameslittle230/stork#26]
The Rust language docs also use a search index. At the moment it's a custom piece of JavaScript. I wonder if Stork could be of interest to use in Rustdoc.

You might find it interesting to chip in on the internals thread https://internals.rust-lang.org/t/rustdoc-use-stork-search-index/12057

**Comment by jameslittle230** [comment]
Hey, that's a good idea! I've reached out on the thread.
