### ISSUE TITLE
Test server does not appear to work

### ISSUE THREAD

**Issue by ankrgyl** [jameslittle230/stork#269]
I am sure I am missing something... so apologies if there is somewhere obvious I should have figured this out. I was attempting to use `stork test` on my newly generated search index, and I encountered a few different issues:

1) The [documentation](https://stork-search.net/docs/build) suggests that you use `stork test --input`; however, the command line appears to want `--config` or `--index`:

```
$ stork test
Error: `Test server requires either --config or --index`
```

2) If you run it with `--index`, you get the same error as above ^^

```
$ stork test --index my-docs.st
Error: `Test server requires either --config or --index`
```

3) If you run it with `--config`, you get an error message that `stork` was not compiled with support for the test server. I tried downloading the Mac OS X release (`./stork-macos-10-15`) and observed the same error.
```
$ stork test --config basic.toml
Stork was not compiled with test server support. Rebuild the crate with default features to enable the test server
```

4) I tried manually compiling with `test-server-enabled` and saw a bunch of errors (but did not investigate further).

It was easy enough to get a basic HTML file + webserver running locally for simple testing, so I'm not at all blocked by this, but thought I'd report it in case it's helpful.

**Comment by jameslittle230** [comment]
Thanks - this was broken for a few different reasons. I put up a PR to fix it and the test server should be working in the next version.
