### ISSUE TITLE
Write contributing.md

### ISSUE THREAD

**Issue by jameslittle230** [jameslittle230/stork#277]
Project's getting some eyes. Help people figure out how to get started, if they want!

**Comment by mmlkrx** [comment]
Hey James, just wanted to +1 this as I'm currently trying out stork for a tiny side project and noticed some outdated documentation. If you need inspiration, feel free to take a look at [Zulip's contributing.md](https://github.com/zulip/zulip/blob/main/CONTRIBUTING.md). Obviously it's a much larger open source project, but cherry picking what applies to stork could be a good start :)

(Personally I really like that they have a section for non-code contributions)
