### ISSUE TITLE
How to configure Stork to ignore <pre> tags?

### ISSUE THREAD

**Issue by ezekg** [jameslittle230/stork#279]
My company's [documentation](https://keygen.sh/docs/api/) has a lot of `<pre>` tags containing code snippets, and Stork seems to be indexing all of these. Is there a way for me to configure Stork to ignore `<pre>` and possibly even `<code>` tags? I tried setting `exclude_html_selector = 'pre'` and also tried `exclude_html_selector = 'pre, code'` but neither seem to have an effect.

I'm guessing this is also why our search index is about 120MB uncompressed, which I'd really like to lower. 😃

**Comment by jameslittle230** [comment]
Hmm, that's not great. I'll take a look and see if `exclude_html_selector` stopped working at some point, and make sure it works with pre tags. Thanks for the report :)

-James

**Comment by ezekg** [comment]
It seems to happen when there are more than 1 `.noindex` tag on a page.

Here's a reproducible test case:

```toml
[input]
exclude_html_selector = '.noindex'
html_selector = 'main'
files = [
  { path = 'index.html', url = '/', title = 'Index' },
]
```

```html
<main>
  <p>DO_INDEX</p>
  <p class='noindex'>DO_NOT_INDEX</p>
  <p class='noindex'>DO_NOT_INDEX</p>
</main>
```

When you run `stork test --config stork.toml`, the word `DO_NOT_INDEX` will be indexed once.

Possibly related to https://github.com/kuchiki-rs/kuchiki/issues/81 and Stork's usage below?

https://github.com/jameslittle230/stork/blob/4d301cd641a09ccd9e7964182b0513761dc3c20b/stork-lib/src/index_v3/build/fill_intermediate_entries/word_list_generators/html_word_list_generator.rs#L50-L54

**Comment by ezekg** [comment]
Here's a failing test for `stork-lib/src/index_v3/build/fill_intermediate_entries/word_list_generators/html_word_list_generator.rs`:

```rust
#[test]
fn test_html_content_extraction_with_multiple_excluded_selectors() {
    run_html_parse_test(
        "This content should be indexed This content should also be indexed",
        Some(".yes"),
        Some(".no"),
        r#"
    <html>
        <head></head>
        <body>
            <h1>This is a title</h1>
            <main>
                <section class="yes" id="first">
                    <p>This content should be indexed</p>
                    <p id="second">This content should also be indexed</p>
                    <p class="no">This content should not be indexed</p>
                    <p class="no">This content should also not be indexed</p>
                </section>
            </main>
        </body>
    </html>"#,
    )
}
```

**Comment by ezekg** [comment]
Thanks for the fix! All `.noindex` tags are now ignored, and our search index is down to 25MB uncompressed. 🖖

**Comment by jameslittle230** [comment]
That's great to hear!
