### ISSUE TITLE
Support for stemmer algo

### ISSUE THREAD

**Issue by grenierdev** [jameslittle230/stork#28]
Might be a good idea to index the word using a stemmer algo.

There's a [Rust implementation](https://github.com/CurrySoftware/rust-stemmers) that could be easily integrated within Stork.

**Comment by jameslittle230** [comment]
Hey, that's a really good idea, definitely one I was hoping to get to someday.

That link might turn someday into a day much closer than I originally expected. :)

I'm going to close the issue (sorry) but will let you know when stemming functionality gets released!
