### ISSUE TITLE
Enable macOS installation via MacPorts

### ISSUE THREAD

**Issue by neirbowj** [jameslittle230/stork#296]
This feature request is to ship Stork via [MacPorts](https://guide.macports.org/chunked/project.contributing.html) for macOS users who do not also use Homebrew.

**Comment by jameslittle230** [comment]
This is a fair feature request. I don't know anything about MacPorts. I can take a crack at this when I have a moment, but if anyone else feels more motivated to contribute a MacPorts Stork Search listing, please feel free.

**Comment by neirbowj** [comment]
This is my first attempt at a new MacPorts port, and I know only a little more than nothing about Rust, so I would welcome any feedback on macports/macports-ports#16067.

**Comment by neirbowj** [comment]
My pull request was merged. It should become possible shortly to install it via

```
$ sudo port install stork
```

**Comment by jameslittle230** [comment]
Wonderful! Thank you, @neirbowj!
