### ISSUE TITLE
API: allow using a local `.wasm` file

### ISSUE THREAD

**Issue by srid** [jameslittle230/stork#317]
**Problem**: The `stork.js` generated in releases is hardcoded to use `https://files.stork-search.net/releases/v1.5.0/stork.wasm`

**Desired behaviour**: I'd like `stork.js` to use a local `stork.wasm` file. i.e.: `https://example.com/stork.js` should use `https://example.com/stork.wasm` automatically.

**Implementation approach:** I could pass the wasm URL (`/stork.wasm` for the above example) explicitly in the `register` function by having it take it as an argument; `register` could, in turn, call `initialize` with that wasm URL, instead of invoking it with empty arguments.

https://github.com/jameslittle230/stork/blob/8550f1fe13c334f16026d53886d3e17ae0193925/js/main.ts#L40-L45

as `initialize` already implements this:

https://github.com/jameslittle230/stork/blob/8550f1fe13c334f16026d53886d3e17ae0193925/js/main.ts#L14-L15

**Alternative approaches:** Or can this desired behavior be achieved in a different way?

**Comment by jameslittle230** [comment]
I believe Stork already supports this!

You can initialize Stork with a self-hosted WASM file. Then, any subsequent operations will use that WASM binary to operate.

You can read more about this on the [Self-hosting documentation page](https://stork-search.net/docs/self-hosting).

Let me know if you have any more questions, or if that documentation page doesn't work for you.

**Comment by srid** [comment]
Ah, nice! I should have read the documentation first :-) I'll try this out now ...

**Comment by srid** [comment]
Okay, so it does work as far as the API goes - but it ends up loading _both_ the local and remote wasm:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/3998/192382013-84743f29-825b-4301-9bd8-5d91254e5064.png">

**Comment by srid** [comment]
Could this be because `register` is calling `initialize`, which loads the default wasm URL (the second one in the screenshot above) in addition to the local one that is loaded when I call `register`? The code I have:

```js
            window.addEventListener('load', function () {
              stork.initialize(baseUrl + '_emanote-static/stork/stork.wasm');
              stork.register(indexName, indexUrl);
            });
```

**Comment by jameslittle230** [comment]
Interesting! Maybe there's a bug.

If you just call `initialize()`, does it load both WASM files?

What happens if you call the "split" API:

```
stork.initialize(yourUrl);
stork.downloadIndex(name, url, options);
stork.attach(name);
```

**Comment by srid** [comment]
> If you just call `initialize()`, does it load both WASM files?

If I do that, I see it loading the remote WASM twice:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/3998/192382721-750577d6-9a3b-4266-af7e-fb103421cae8.png">

The above behaviour was for this code:

```js
            window.addEventListener('load', function () {
              stork.initialize(); // (baseUrl + '_emanote-static/stork/stork.wasm');
              stork.register(indexName, indexUrl);
            });
```

> What happens if you call the "split" API:

It still loads both local and remove wasm:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/3998/192383009-a2bdefb3-55c3-412f-9aab-aa8c5bc0b309.png">

```js
            window.addEventListener('load', function () {
              stork.initialize(baseUrl + '_emanote-static/stork/stork.wasm');
              // stork.register(indexName, indexUrl);
              stork.downloadIndex(indexName, indexUrl, {});
              stork.attach(indexName);
            });
```

**Comment by jameslittle230** [comment]
Hm - I'm having trouble reproducing it. When I call your original code in a Codepen, I'm only seeing one WASM blob load.

![Screenshot 2022-09-26T17 33 52@2x](https://user-images.githubusercontent.com/3058200/192384948-c502ca98-16fc-41fa-98d0-03af757d24a9.png)

https://codepen.io/littleguy230/pen/poVpyQm

Are you sure this is the only time your code is interacting with Stork? No other calls to `initialize()` anywhere else?

**Comment by srid** [comment]
You are right; the issue is not with stork per se. It is to do with some other library I'm using, specifically, https://github.com/patrick-steele-idem/morphdom (used in route switch to replace HTML fast), which https://ema.srid.ca/ (used in Emanote) uses. 

I confirmed it by checking the fully statically generated website, which does work per instructions at https://stork-search.net/docs/self-hosting 

Sorry for the false alarm.

**Comment by srid** [comment]
I'm guessing morphdom is double-loading `stork.js` which somehow loads the default wasm when initialize/register is not called in time?
