### ISSUE TITLE
Add stork.js.map to github release assets

### ISSUE THREAD

**Issue by kukimik** [jameslittle230/stork#322]
Hello! Could you please include the source map file `stork.js.map` in the github release assets? Currently the file is [available via CDN](https://github.com/jameslittle230/stork/issues/216), but not in the [github release](https://github.com/jameslittle230/stork/releases/tag/v1.5.0). When one uses the files provided in the github release, it is easy to miss it, which in turn results in the missing source map error. Finding out that the file is available elsewhere is not obvious (I found it via #216 using the github search tool, which is not a very user-friendly way :wink: .)

**Comment by jameslittle230** [comment]
Good catch - thanks! I've added the map file to the release, and I'll change the release process to make sure that the map file is added in future releases.

-James
