### ISSUE TITLE
Working with Subtitles | timestamp_format "MinutesAndSeconds"

### ISSUE THREAD

**Issue by selamhabibi** [jameslittle230/stork#330]
In the Stork-Search documentation you can find an example for searching within a SRT file using the "Vimeo format":

https://stork-search.net/docs/srt

The option "timestamp_format = "MinutesAndSeconds" for rendering in minutes and seconds is not available in the current version.

I have tried the pre-compiled binary version 1.5 for macOS and Ubuntu version

This is the error I get:

Couldn't read the configuration file: Cannot parse config as TOML. Stork recieved error: `unknown variant `MinutesAndSeconds`, expected `number_of_seconds` for key `input.srt_config.timestamp_format` at line 4 column 1` 

I could only test "timestamp_format = "NumberOfSeconds" successfully.
In which version was the "Vimeo format" taken into account?

**Comment by jameslittle230** [comment]
@selamhabibi - Good catch. Somehow that made it into the documentation (many months ago) despite the feature having never existed.

In the next release, I'll add this feature, making the documentation correct.

-James

**Comment by jameslittle230** [comment]
I've pushed a PR that adds the feature, and I'll publish a release tomorrow that includes it. Thanks again for reporting!
