### ISSUE TITLE
at some point, content stops being indexed

### ISSUE THREAD

**Issue by setop** [jameslittle230/stork#69]
Hi,

Thank for this great tool. I'm starting to integrate it into my blog.

However, it seems that very small portion of each file is indexed. After further investigation it seems to stop at the first character not being a letter or a digit or space.

To confirm that I've created a text of plain English. Just by putting a double quote (") alone anywhere in the middle, it stops the indexation. Meaning I can find words before but not a word after. I'm sure other non alphanumeric can trigger that as not all my input files have double quotes.

I have started looking at WordListGenerators but unfortunately I'm not skilled enough in Rust to see what's happening.

Regards

**Comment by jameslittle230** [comment]
@setop --

This is _definitely_ not what's supposed to be happening -- thanks for pointing it out.

I'll try to have a hotfix released as soon as I can.

Best,
James

**Comment by jameslittle230** [comment]
@setop,
I've managed to reproduce the bug, and am working on a fix.

**Comment by jameslittle230** [comment]
@setop ,
I've released [Stork 0.7.4](https://github.com/jameslittle230/stork/releases/tag/v0.7.4) with (what I think is) a fix for the bug you've described.

If you get a chance, please update your installed version of Stork, rebuild your index, and let me know if the bug has been fixed for you.

Thanks again,
James

**Comment by setop** [comment]
You're fast at fixing !

Yes it seems to work perfectly.

Thanks a lot.

**Comment by jameslittle230** [comment]
@setop -

Thanks for reporting the bug -- I really appreciate it. 

If you have any more feedback, questions, or bug reports as you work with Stork, I'd love to hear from you. 

James
