### ISSUE TITLE
Question/Feature : Build an index in the browser

### ISSUE THREAD

**Issue by talolard** [jameslittle230/stork#84]
**Is your feature request related to a problem? Please describe.**
I'd like to let my users upload a JSON/csv of documents and build an index in the client.

**Describe the solution you'd like**
A webassembly engine for building indexes and the JS APIs for it. 

**Describe alternatives you've considered**
I currently use [NDX](https://github.com/ndx-search/ndx) and build the index in a webworker. 
I'm looking for a few missing features 

**Additional context**
I'm not sure if this is possible in stork already ?

**Comment by jameslittle230** [comment]
Hey, thanks for writing in! This is not something that Stork supports today, nor is it on the roadmap, but I'll keep it in mind for future work. 

Going to close the issue, but feel free to reopen and add comments if you have any more thoughts or questions!

Best,
James
