### ISSUE TITLE
Some words not searchable

### ISSUE THREAD

**Issue by DanilaFe** [jameslittle230/stork#95]
Hi! 

I'm running into an issue where I'm unable to search for certain words in my index; in particular, I seem to run into issues with "intro" and "polymorphism". I have a series of blog posts. When I search them by number, their titles show up in the search list:

![Screenshot_2020-12-27 Daniel's Blog(6)](https://user-images.githubusercontent.com/4361282/103189852-796c7a00-4883-11eb-8e13-617e1dd8181f.png)

However, when I try to look them up by keywords, I don't get the relevant results:

![Screenshot_2020-12-27 Daniel's Blog(5)](https://user-images.githubusercontent.com/4361282/103189916-a6209180-4883-11eb-9f2c-8502e66cb37a.png)

The word "introduction" shows up, but not "intro"! A similar thing happens with "polymorphism". It's there when I search by part number, but any prefix of the string ("pol", "poly", and so on) doesn't give me any relevant results. I suspect that this may be the case because "polymorphism" is a rather uncommon word, and "intro" may technically not be a word at all, but a slang contraction of "introduction".

I'm not sure what kind of information would be helpful in debugging this. I can say, though, that this occurs even when the relevant file / article is the _only_ one being indexed. Attached are two index files,  [one with all articles](https://github.com/jameslittle230/stork/files/5745885/index.st.zip), and [one with just the polymorphism article](https://github.com/jameslittle230/stork/files/5745886/index.st.min.zip).

Thank you for making Stork!

**Comment by Arjan321** [comment]
I seem to have a similar issue where looking for "gallery" results in no results, despite 83 occurrences in the source Markdowns

**Comment by jameslittle230** [comment]
This is bizarre! I'm tracking down the bug now, and will let you know when this is fixed!

**Comment by jameslittle230** [comment]
@DanilaFe - would you mind sending your config file over? I have a hunch about what the issue is but if I know how your index is being generated, it'll help me narrow down the options faster.

Appreciate it (and thank you for such a thorough bug report!)

James

**Comment by jameslittle230** [comment]
Reasonably sure that #98 fixes this bug. I'll release this in 1.0.1 today -- you'll have to rebuild your index after upgrading to see the fix.

Let me know if this fixes the bug you're seeing, otherwise, please feel free to reopen the issue and I'll see what I can find!

**Comment by DanilaFe** [comment]
Thanks for taking a look so quickly! I will upload the configuration file and some corresponding markdown posts (as well as reopen the issue) if the bug persists.
